import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { inventoryCategories, inventoryItems } from "@/data/inventory";

export const metadata: Metadata = { title: "Inventory", description: "Explore public event equipment categories from Elroy Events." };

export default function InventoryPage() { return <div><section className="bg-navy pb-20 pt-40 text-white"><div className="container-shell"><p className="eyebrow text-white/60">Public catalogue</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold sm:text-6xl">Equipment for the occasion.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">Browse a selection of event essentials. Availability and final recommendations are confirmed when we prepare your quotation.</p></div></section><section className="container-shell py-20"><div className="flex flex-wrap gap-2">{inventoryCategories.map((category) => <span key={category} className="rounded-full border border-navy/15 px-4 py-2 text-sm text-navy/70">{category}</span>)}</div><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{inventoryItems.map((item) => <article key={item.name} className="overflow-hidden rounded-sm border border-navy/10 bg-canvas transition hover:shadow-soft"><div className="relative aspect-[4/3] bg-[#f4f5f2]"><Image src={item.image} alt={item.alt} fill className="object-cover" sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" /></div><div className="p-6"><div className="flex items-center justify-between gap-3"><p className="eyebrow">{item.category}</p><span className="inline-flex items-center gap-1 text-xs text-navy/50"><Check size={13} className="text-burgundy" /> Quote-based</span></div><h2 className="mt-3 text-xl font-semibold">{item.name}</h2><p className="mt-3 text-sm leading-6 text-navy/60">{item.description}</p><Button asChild variant="ghost" className="mt-5 px-0"><Link href={`/get-a-quote?equipment=${encodeURIComponent(item.name)}`}>Request a quote <ArrowRight className="ml-2" size={16} /></Link></Button></div></article>)}</div><div className="mt-16 rounded-sm bg-burgundy p-8 text-white sm:p-12"><p className="eyebrow text-white/70">Looking for something specific?</p><div className="mt-4 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><h2 className="max-w-xl text-3xl font-semibold">Tell us about your guest count, venue and date.</h2><Button asChild variant="secondary"><Link href="/get-a-quote">Start a request <ArrowRight className="ml-2" size={17} /></Link></Button></div></div></section></div>; }
