import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, Check, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { services } from "@/data/services";
import { strengths } from "@/data/strengths";

const events = [
  { category: "Wedding", title: "An evening to remember", image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85" },
  { category: "Corporate", title: "Ideas in good company", image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=85" },
  { category: "Private event", title: "The details make the day", image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=85" },
];

const process = ["Consultation", "Planning", "Setup & execution", "Event completion"];

export default function HomePage() {
  return <div>
    <section className="relative flex min-h-[720px] items-end overflow-hidden bg-navy pb-20 pt-40 text-white">
      <Image src="https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=2200&q=85" alt="Elegant event tent prepared for a celebration" fill priority className="object-cover opacity-50" sizes="100vw" />
      <div className="absolute inset-0 bg-gradient-to-t from-navy via-navy/55 to-navy/20" />
      <div className="container-shell relative"><p className="eyebrow text-white/70">Events, thoughtfully delivered</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[1.08] sm:text-6xl lg:text-7xl">Creating <span className="text-burgundy">extraordinary</span> events.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/75">Premium event planning, equipment rental and professional event solutions for unforgettable experiences.</p><div className="mt-9 flex flex-wrap gap-4"><Button asChild size="lg"><Link href="/get-a-quote">Get a Quote <ArrowRight className="ml-2" size={18} /></Link></Button><Button asChild variant="secondary" size="lg"><Link href="/services">Explore Our Services</Link></Button></div></div>
      <div className="absolute bottom-7 left-1/2 -translate-x-1/2 text-white/60" aria-hidden="true"><ArrowDown className="animate-bounce" size={20} /></div>
    </section>

    <section className="container-shell grid gap-12 py-24 lg:grid-cols-[1fr_1.35fr] lg:items-center"><div><p className="eyebrow">The Elroy standard</p><h2 className="mt-4 text-4xl font-semibold leading-tight sm:text-5xl">Everything you need for an exceptional event.</h2></div><div><p className="text-lg leading-8 text-navy/65">From the first conversation to the final guest departure, Elroy Events brings together dependable equipment, considered design and an experienced team to make your event feel effortless.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{["Premium equipment", "Reliable delivery", "Professional team", "Quality execution"].map(item => <div key={item} className="flex items-center gap-3 font-semibold"><span className="grid h-7 w-7 place-items-center rounded-full bg-burgundy/10 text-burgundy"><Check size={15} /></span>{item}</div>)}</div></div></section>

    <section className="bg-[#f4f5f2] py-24"><div className="container-shell"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">What we do</p><h2 className="mt-4 text-4xl font-semibold">Solutions for every occasion.</h2></div><Link className="font-semibold text-burgundy hover:underline" href="/services">View all services <ArrowRight className="ml-1 inline" size={16} /></Link></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.slice(0, 6).map((service, index) => { const Icon = service.icon; return <article key={service.title} className="group rounded-sm bg-canvas p-7 shadow-soft transition hover:-translate-y-1"><div className="flex items-start justify-between"><Icon className="text-burgundy" size={25} strokeWidth={1.5} /><span className="font-stat text-sm text-navy/35">0{index + 1}</span></div><h3 className="mt-10 text-xl font-semibold">{service.title}</h3><p className="mt-3 text-sm leading-6 text-navy/60">{service.description}</p><Link className="mt-6 inline-block text-sm font-semibold text-burgundy" href="/services">View details <ArrowRight className="ml-1 inline" size={15} /></Link></article>; })}</div></div></section>

    <section className="container-shell py-24"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Selected moments</p><h2 className="mt-4 text-4xl font-semibold">Made for the moments that matter.</h2></div><Link className="font-semibold text-burgundy hover:underline" href="/gallery">View our gallery <ArrowRight className="ml-1 inline" size={16} /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{events.map(event => <Link href="/gallery" key={event.title} className="group relative min-h-[360px] overflow-hidden rounded-sm bg-navy text-white"><Image src={event.image} alt={event.title} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(min-width: 768px) 33vw, 100vw" /><div className="absolute inset-0 bg-gradient-to-t from-navy via-transparent to-transparent" /><div className="absolute inset-x-6 bottom-6"><p className="eyebrow text-white/70">{event.category}</p><h3 className="mt-2 text-2xl font-semibold">{event.title}</h3><ChevronRight className="mt-4 text-burgundy transition group-hover:translate-x-1" /></div></Link>)}</div></section>

    <section className="bg-navy py-24 text-white"><div className="container-shell"><div className="max-w-2xl"><p className="eyebrow text-white/60">Why Elroy Events</p><h2 className="mt-4 text-4xl font-semibold sm:text-5xl">Confidence in every detail.</h2></div><div className="mt-12 grid gap-8 md:grid-cols-2 lg:grid-cols-4">{strengths.map(({ title, description, icon: Icon }) => <div key={title} className="border-t border-white/15 pt-6"><Icon className="text-burgundy" size={27} strokeWidth={1.5} /><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{description}</p></div>)}</div></div></section>

    <section className="container-shell py-24"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.4fr] lg:items-center"><div><p className="eyebrow">How it works</p><h2 className="mt-4 text-4xl font-semibold">A clear path to a remarkable event.</h2></div><div className="grid gap-0 sm:grid-cols-4">{process.map((step, index) => <div key={step} className="relative border-l border-navy/15 px-5 py-4 first:border-l-0 sm:border-l"><span className="font-stat text-sm text-burgundy">0{index + 1}</span><h3 className="mt-5 font-semibold">{step}</h3></div>)}</div></div></section>

    <section className="container-shell pb-24"><div className="rounded-sm bg-navy p-8 text-white sm:p-14 lg:flex lg:items-center lg:justify-between"><div><p className="eyebrow text-white/60">Ready when you are</p><h2 className="mt-4 max-w-xl text-4xl font-semibold">Let&apos;s create something remarkable.</h2><p className="mt-4 max-w-lg text-white/65">Tell us what you&apos;re planning and we&apos;ll help bring the details together.</p></div><Button asChild size="lg" className="mt-8 shrink-0 lg:mt-0"><Link href="/get-a-quote">Start a conversation <ArrowRight className="ml-2" size={18} /></Link></Button></div></section>
  </div>;
}
