import type { Metadata } from "next";
import { CalendarDays, Mail, MapPin, Phone } from "lucide-react";
import { QuoteForm } from "@/components/forms/quote-form";

export const metadata: Metadata = { title: "Get a Quote", description: "Request a quote for your next event with Elroy Events." };

export default function QuotePage() {
  return <div><section className="bg-navy pb-20 pt-40 text-white"><div className="container-shell"><p className="eyebrow text-white/60">Request your quote</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold sm:text-6xl">Tell us about your event.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">Share your plans and we&apos;ll prepare a tailored recommendation for your venue, guest count and preferred setup.</p></div></section><section className="container-shell py-20"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div className="rounded-sm border border-navy/10 bg-[#f4f5f2] p-8"><h2 className="text-2xl font-semibold">Quick info</h2><div className="mt-8 space-y-5 text-sm text-navy/70"><div className="flex items-start gap-3"><Phone className="mt-0.5 text-burgundy" size={18} /><div><p className="font-semibold text-navy">Call us</p><p>+254 700 000 000</p></div></div><div className="flex items-start gap-3"><Mail className="mt-0.5 text-burgundy" size={18} /><div><p className="font-semibold text-navy">Email</p><p>hello@elroyevents.co.ke</p></div></div><div className="flex items-start gap-3"><MapPin className="mt-0.5 text-burgundy" size={18} /><div><p className="font-semibold text-navy">Location</p><p>Kenya · By appointment</p></div></div><div className="flex items-start gap-3"><CalendarDays className="mt-0.5 text-burgundy" size={18} /><div><p className="font-semibold text-navy">Planning window</p><p>Share your date as early as possible.</p></div></div></div></div><QuoteForm /></div></section></div>;
}
